import { prisma } from "@repo/database";

export const findMissingBrands = async () => {
  const dbBrands = await prisma.brand.findMany({
    where: {
      inTrash: false,
      deletedAt: null,
    },
    select: {
      id: true,
      name: true,
      label: true,
    },
  });

  const matcherBrands = new Set(
    Object.keys(brandMatcher).map((key) => key.toLowerCase())
  );

  const missingBrands = dbBrands.filter((brand) => {
    const brandName = brand.name.toLowerCase();
    const brandLabel = brand.label?.toLowerCase();

    return (
      !matcherBrands.has(brandName) ||
      (brandLabel && brandLabel !== brandName && !matcherBrands.has(brandLabel))
    );
  });

  // Add missing brands to the brandMatcher object
  missingBrands.forEach((brand) => {
    const brandName = brand.name.toLowerCase();
    const brandLabel = brand.label?.toLowerCase();

    // Create enum key from brand name
    const enumKey = brand.name.replace(/[^a-zA-Z0-9]/g, "");

    // Add brand name to matcher if missing
    if (!matcherBrands.has(brandName)) {
      (brandMatcher as any)[brandName] = brand.name;
    }

    // Add brand label to matcher if it exists and is different from name
    if (
      brandLabel &&
      brandLabel !== brandName &&
      !matcherBrands.has(brandLabel)
    ) {
      (brandMatcher as any)[brandLabel] = brand.name;
    }
  });
};

const brands = {
  "basic stitches": ["basicstitches", "basic stitches"],
  "denim label": ["denimlabel", "denim label"],
  "double a": ["doublea", "double a"],
  "katee by kristina": ["kateebykristina", "katee by kristina"],
  "frill n wear": ["frillnwear", "frill n wear"],
  "euphoria denims": ["euphoriadenims", "euphoria denims"],
  "the preppy society": [
    "thepreppysociety",
    "the preppy society",
    "preppysociety",
    "preppy society",
  ],
  "daar dahlia": ["daardahlia", "daar dahlia"],
  sweep: ["sweep"],
  "mirna nakhla": ["mirnanakhla", "mirna nakhla"],
  seashell: ["seashell"],
  "black edition": ["blackedition", "black edition"],
  "brown toast": ["browntoast", "brown toast"],
  "boujee lane": ["boujeelane", "boujee lane"],
  "the basic look": [
    "thebasiclook",
    "the basic look",
    "basic look",
    "basiclook",
  ],
  "baggy collective": ["baggycollective", "baggy collective"],
  "ctrl cairo": ["ctrlcairo", "ctrl cairo"],
  "designed by ducky": ["designedbyducky", "designed by ducky"],
  "sa studio": ["sastudio", "sa studio"],
  "null beings": ["nullbeings", "null beings"],
  "little lads": ["littlelads", "little lads"],
  coddiwomple: ["coddiwomple", "coddi womple", "codi womple"],
  jiggyandco: ["jiggyandco", "jiggy and co"],
  twoguys: ["twoguys", "two guys"],
  "the stahps": ["thestahps", "the stahps"],
  "basic couture": ["basiccouture", "basic couture"],
  nashecollection: ["nashecollection", "nashe collection"],
  "ordinary product": ["ordinaryproduct", "ordinary product"],
  ppanther: ["ppanther", "p panther"],
  homeboyattire: ["homeboyattire", "homeboy attire"],
  designkaf: ["designkaf", "design kaf"],
  fullslang: ["fullslang", "full slang"],
  "be indie": ["beindie", "be indie"],
  hrtbrk: ["hrtbrk", "hrt brk"],
  "fehe concept": ["feheconcept", "fehe concept"],
  alcamileon: ["alcamileon", "al camileon"],
  "99 threads": ["99threads", "99 threads"],
  thewpclub: ["thewpclub", "the wp club", "the wpclub"],
  "maison dousha": ["maisondousha", "maison dousha"],
  konga: ["konga"],
  daddysgirl: ["daddysgirl"],
  blnco: ["blnco"],
  soul: ["soul"],
  terre: ["terre"],
  wahm: ["wahm"],
  dodici: ["dodici"],
  organdy: ["organdy"],
  bazic: ["bazic"],
  moshpits: ["moshpits"],
  fling: ["fling"],
  almah: ["almah"],
  ray: ["ray"],
  mad: ["mad"],
  clarified: ["clarified"],
  doxx: ["doxx"],
  taycan: ["taycan"],
  "am pm": ["ampm", "am pm"],
  frenchee: ["frenchee"],
  maiia: ["maiia"],
  navy: ["nav"],
  psych: ["psych"],
  mgmp: ["mgmp"],
  quwa: ["quwa"],
  aja: ["aja"],
  notfound: ["notfound"],
  jai: ["jai"],
  spaceout: ["spaceout"],
  stps: ["stps"],
  tamo: ["tamo"],
  musts: ["musts"],
  totelly: ["totelly"],
  forme: ["forme"],
  elemnts: ["elemnts"],
  hudz: ["hudz"],
  seemly: ["seemly"],
  haze: ["haze"],
  madehill: ["madehill"],
  freyya: ["freyya"],
  zei: ["zei"],
  moongie: ["moongie"],
  nare: ["nare"],
  ayo: ["ayo"],
  takeover: ["takeover"],
  peppers: ["peppers"],
  blameworthy: ["blameworthy"],
  abstract: ["abstract"],
  manifest: ["manifest"],
  vulaire: ["vulaire"],
  elodie: ["elodie"],
  kush: ["kush"],
  theworkshopxx: ["theworkshopxx"],
  unty: ["unty"],
  denjo: ["denjo"],
  blac: ["blac"],
  zuri: ["zuri"],
  ausetia: ["ausetia"],
  loafers: ["loafers"],
  najlah: ["najlah"],
  meiji: ["meiji"],
  nash: ["nash"],
  palma: ["palma"],
  shopwithpink: ["shopwithpink"],
  escala: ["escala"],
  antidote: ["antidote"],
  ghazl: ["ghazl"],
  dnm: ["dnm"],
  juvenile: ["juvenile"],
  runes: ["runes"],
  sundaysbest: ["sundaysbest"],
  kijaqo: ["kijaqo"],
  "3einn": ["3einn"],
  mfns: ["mfns"],
  locken: ["locken"],
  nothingnice: ["nothingnice"],
  elpatron: ["elpatron"],
  boujee: ["boujee"],
  noumi: ["noumi"],
  thea: ["thea"],
  amgaad: ["amgaad"],
  staygamed: ["staygamed"],
  cielo: ["cielo"],
  glitch: ["glitch"],
  horra: ["horra"],
  minerva: ["minerva"],
  taysa: ["taysa"],
  mayaba: ["mayaba"],
  "8tsh": ["8tsh"],
  crunk: ["crunk"],
  beyond: ["beyond"],
  leaf: ["leaf"],
  leil: ["leil"],
  nuude: ["nuude"],
  alyqza: ["alyqza"],
  camo: ["camo"],
  kracked: ["kracked"],
  warped: ["warped"],
  urbns: ["urbns"],
  vega: ["vega"],
  core: ["core"],
  lalas: ["lalas"],
  chav: ["chav"],
  myne: ["myne"],
  mzaco: ["mzaco"],
  leon: ["leon"],
  minilet: ["minilet"],
  slack: ["slack"],
  fufa: ["fufa"],
  kulture: ["kulture"],
  kato: ["kato"],
  riddle: ["riddle"],
  replica: ["replica"],
  kangaroo: ["kangaroo"],
  azelea: ["azelea"],
  asili: ["asili"],
  stache: ["stache"],
  nspired: ["nspired"],
  odd: ["odd"],
  silq: ["silq"],
  fools: ["fools"],
  pulp: ["pulp"],
  novencci: ["novencci"],
  greaze: ["greaze"],
  illusion: ["illusion"],
  bazets: ["bazets"],
  lumaa: ["lumaa"],
  sass: ["sass"],
  kuji: ["kuji"],
  tamaa: ["tamaa"],
  clother: ["clother"],
  locco: ["locco"],
  kika: ["kika"],
  antikka: ["antikka"],
};

enum b {
  Jadilah = "jadilah",
  Secret = "secret",
  Kloth = "kloth",
  LeenaAndeel = "leena andeel",
  Niffty = "niffty",
  Vinci = "Vinci",
  Capsule = "capsule",
  Konga = "konga",
  BasicStitches = "basic stitches",
  DaddysGirl = "daddysgirl",
  Blnco = "blnco",
  Soul = "soul",
  Terre = "terre",
  Wahm = "wahm",
  DenimLabel = "denim label",
  DoubleA = "double a",
  Dodici = "dodici",
  KateeByKristina = "katee by kristina",
  Organdy = "organdy",
  FrillNWear = "frill n wear",
  Bazic = "bazic",
  Moshpits = "moshpits",
  Fling = "fling",
  Almah = "almah",
  Ray = "ray",
  Mad = "mad",
  Clarified = "clarified",
  EuphoriaDenims = "euphoria denims",
  Doxx = "doxx",
  Taycan = "taycan",
  AmPm = "am pm",
  Frenchee = "frenchee",
  Maiia = "maiia",
  Navy = "navy",
  ThePreppySociety = "the preppy society",
  Psych = "psych",
  Mgmp = "mgmp",
  Quwa = "quwa",
  Aja = "aja",
  Notfound = "notfound",
  Jai = "jai",
  DaarDahlia = "daar dahlia",
  Sweep = "sweep",
  MirnaNakhla = "mirna nakhla",
  Seashell = "seashell",
  BlackEdition = "black edition",
  Spaceout = "spaceout",
  Stps = "stps",
  Tamo = "tamo",
  Musts = "musts",
  Totelly = "totelly",
  Forme = "forme",
  BrownToast = "brown toast",
  Elemnts = "elemnts",
  Hudz = "hudz",
  Seemly = "seemly",
  Haze = "haze",
  Madehill = "madehill",
  BoujeeLane = "boujee lane",
  TheBasicLook = "the basic look",
  Freyya = "freyya",
  Zei = "zei",
  BaggyCollective = "baggy collective",
  Moongie = "moongie",
  Nare = "nare",
  Ayo = "ayo",
  Takeover = "takeover",
  CtrlCairo = "ctrl cairo",
  Peppers = "peppers",
  Blameworthy = "blameworthy",
  Abstract = "abstract",
  DesignedByDucky = "designed by ducky",
  Manifest = "manifest",
  Vulaire = "vulaire",
  Elodie = "elodie",
  Kush = "kush",
  Theworkshopxx = "theworkshopxx",
  Unty = "unty",
  Denjo = "denjo",
  Blac = "blac",
  Zuri = "zuri",
  SaStudio = "sa studio",
  Ausetia = "ausetia",
  Loafers = "loafers",
  Najlah = "najlah",
  Meiji = "meiji",
  Nash = "nash",
  Palma = "palma",
  Shopwithpink = "shopwithpink",
  Escala = "escala",
  Antidote = "antidote",
  Ghazl = "ghazl",
  NullBeings = "null beings",
  Dnm = "dnm",
  Juvenile = "juvenile",
  Runes = "runes",
  LittleLads = "little lads",
  Sundaysbest = "sundaysbest",
  Kijaqo = "kijaqo",
  "3einn" = "3einn",
  Mfns = "mfns",
  Locken = "locken",
  Nothingnice = "nothingnice",
  Elpatron = "elpatron",
  Boujee = "boujee",
  Noumi = "noumi",
  Thea = "thea",
  Amgaad = "amgaad",
  Staygamed = "staygamed",
  Cielo = "cielo",
  Glitch = "glitch",
  Horra = "horra",
  Minerva = "minerva",
  Coddiwomple = "coddiwomple",
  Taysa = "taysa",
  Jiggyandco = "jiggyandco",
  Mayaba = "mayaba",
  "8tsh" = "8tsh",
  Crunk = "crunk",
  Beyond = "beyond",
  Leaf = "leaf",
  Leil = "leil",
  Twoguys = "twoguys",
  TheStahps = "the stahps",
  Nuude = "nuude",
  Alyqza = "alyqza",
  Camo = "camo",
  Kracked = "kracked",
  Warped = "warped",
  Urbns = "urbns",
  BasicCouture = "basic couture",
  Vega = "vega",
  Core = "core",
  Lalas = "lalas",
  Chav = "chav",
  Nashecollection = "nashecollection",
  OrdinaryProduct = "ordinary product",
  Ppanther = "ppanther",
  Myne = "myne",
  Mzaco = "mzaco",
  Leon = "leon",
  Minilet = "minilet",
  Homeboyattire = "homeboyattire",
  Designkaf = "designkaf",
  Slack = "slack",
  Fufa = "fufa",
  Fullslang = "fullslang",
  Kulture = "kulture",
  Kato = "kato",
  Riddle = "riddle",
  Replica = "replica",
  Kangaroo = "kangaroo",
  Azelea = "azelea",
  BeIndie = "be indie",
  Asili = "asili",
  Stache = "stache",
  Nspired = "nspired",
  Odd = "odd",
  Silq = "silq",
  Hrtbrk = "hrtbrk",
  Fools = "fools",
  Pulp = "pulp",
  Novencci = "novencci",
  FeheConcept = "fehe concept",
  Greaze = "greaze",
  Illusion = "illusion",
  Bazets = "bazets",
  Lumaa = "lumaa",
  Sass = "sass",
  Kuji = "kuji",
  Tamaa = "tamaa",
  Alcamileon = "alcamileon",
  Clother = "clother",
  "99Threads" = "99 threads",
  Thewpclub = "thewpclub",
  Locco = "locco",
  Kika = "kika",
  Antikka = "antikka",
  MaisonDousha = "maison dousha",
}

// reverse the brands object
// const reverseBrands = Object.entries(brands).reduce(
//   (acc, [key, value]) => {
//     value.forEach((v) => {
//       acc[v] = key as b;
//     });
//     return acc;
//   },
//   {} as Record<string, b>
// );

// console.log(reverseBrands);

export const brandMatcher: Record<string, b> = {
  jadilah: b.Jadilah,
  secret: b.Secret,
  kloth: b.Kloth,
  "by leena andeel": b.LeenaAndeel,
  byleenaandeel: b.LeenaAndeel,
  leenaandeel: b.LeenaAndeel,
  "leena andeel": b.LeenaAndeel,
  niffty: b.Niffty,
  vinci: b.Vinci,
  capsule: b.Capsule,
  konga: b.Konga,
  basicstitches: b.BasicStitches,
  "basic stitches": b.BasicStitches,
  "daddy's girl": b.DaddysGirl,
  "daddys girl": b.DaddysGirl,
  daddysgirl: b.DaddysGirl,
  blnco: b.Blnco,
  soul: b.Soul,
  terre: b.Terre,
  wahm: b.Wahm,
  denimlabel: b.DenimLabel,
  "denim label": b.DenimLabel,
  doublea: b.DoubleA,
  "double a": b.DoubleA,
  dodici: b.Dodici,
  kateebykristina: b.KateeByKristina,
  "katee by kristina": b.KateeByKristina,
  organdy: b.Organdy,
  frillnwear: b.FrillNWear,
  "frill n wear": b.FrillNWear,
  bazic: b.Bazic,
  moshpits: b.Moshpits,
  fling: b.Fling,
  almah: b.Almah,
  ray: b.Ray,
  mad: b.Mad,
  clarified: b.Clarified,
  euphoriadenims: b.EuphoriaDenims,
  "euphoria denims": b.EuphoriaDenims,
  doxx: b.Doxx,
  taycan: b.Taycan,
  ampm: b.AmPm,
  "am pm": b.AmPm,
  frenchee: b.Frenchee,
  maiia: b.Maiia,
  nav: b.Navy,
  thepreppysociety: b.ThePreppySociety,
  "the preppy society": b.ThePreppySociety,
  preppysociety: b.ThePreppySociety,
  "preppy society": b.ThePreppySociety,
  psych: b.Psych,
  mgmp: b.Mgmp,
  quwa: b.Quwa,
  aja: b.Aja,
  notfound: b.Notfound,
  jai: b.Jai,
  daardahlia: b.DaarDahlia,
  "daar dahlia": b.DaarDahlia,
  sweep: b.Sweep,
  mirnanakhla: b.MirnaNakhla,
  "mirna nakhla": b.MirnaNakhla,
  seashell: b.Seashell,
  blackedition: b.BlackEdition,
  "black edition": b.BlackEdition,
  spaceout: b.Spaceout,
  stps: b.Stps,
  tamo: b.Tamo,
  musts: b.Musts,
  totelly: b.Totelly,
  forme: b.Forme,
  browntoast: b.BrownToast,
  "brown toast": b.BrownToast,
  elemnts: b.Elemnts,
  hudz: b.Hudz,
  seemly: b.Seemly,
  haze: b.Haze,
  madehill: b.Madehill,
  boujeelane: b.BoujeeLane,
  "boujee lane": b.BoujeeLane,
  thebasiclook: b.TheBasicLook,
  "the basic look": b.TheBasicLook,
  "basic look": b.TheBasicLook,
  basiclook: b.TheBasicLook,
  freyya: b.Freyya,
  zei: b.Zei,
  baggycollective: b.BaggyCollective,
  "baggy collective": b.BaggyCollective,
  moongie: b.Moongie,
  nare: b.Nare,
  ayo: b.Ayo,
  takeover: b.Takeover,
  ctrlcairo: b.CtrlCairo,
  "ctrl cairo": b.CtrlCairo,
  peppers: b.Peppers,
  blameworthy: b.Blameworthy,
  abstract: b.Abstract,
  designedbyducky: b.DesignedByDucky,
  "designed by ducky": b.DesignedByDucky,
  manifest: b.Manifest,
  vulaire: b.Vulaire,
  elodie: b.Elodie,
  kush: b.Kush,
  theworkshopxx: b.Theworkshopxx,
  unty: b.Unty,
  denjo: b.Denjo,
  blac: b.Blac,
  zuri: b.Zuri,
  sastudio: b.SaStudio,
  "sa studio": b.SaStudio,
  ausetia: b.Ausetia,
  loafers: b.Loafers,
  najlah: b.Najlah,
  meiji: b.Meiji,
  nash: b.Nash,
  palma: b.Palma,
  shopwithpink: b.Shopwithpink,
  escala: b.Escala,
  antidote: b.Antidote,
  ghazl: b.Ghazl,
  nullbeings: b.NullBeings,
  "null beings": b.NullBeings,
  dnm: b.Dnm,
  juvenile: b.Juvenile,
  runes: b.Runes,
  littlelads: b.LittleLads,
  "little lads": b.LittleLads,
  sundaysbest: b.Sundaysbest,
  kijaqo: b.Kijaqo,
  "3einn": b["3einn"],
  mfns: b.Mfns,
  locken: b.Locken,
  nothingnice: b.Nothingnice,
  elpatron: b.Elpatron,
  boujee: b.Boujee,
  noumi: b.Noumi,
  thea: b.Thea,
  amgaad: b.Amgaad,
  staygamed: b.Staygamed,
  cielo: b.Cielo,
  glitch: b.Glitch,
  horra: b.Horra,
  minerva: b.Minerva,
  coddiwomple: b.Coddiwomple,
  "coddi womple": b.Coddiwomple,
  "codi womple": b.Coddiwomple,
  taysa: b.Taysa,
  jiggyandco: b.Jiggyandco,
  "jiggy and co": b.Jiggyandco,
  mayaba: b.Mayaba,
  "8tsh": b["8tsh"],
  crunk: b.Crunk,
  beyond: b.Beyond,
  leaf: b.Leaf,
  leil: b.Leil,
  twoguys: b.Twoguys,
  "two guys": b.Twoguys,
  thestahps: b.TheStahps,
  "the stahps": b.TheStahps,
  nuude: b.Nuude,
  alyqza: b.Alyqza,
  camo: b.Camo,
  kracked: b.Kracked,
  warped: b.Warped,
  urbns: b.Urbns,
  basiccouture: b.BasicCouture,
  "basic couture": b.BasicCouture,
  vega: b.Vega,
  core: b.Core,
  lalas: b.Lalas,
  chav: b.Chav,
  nashecollection: b.Nashecollection,
  "nashe collection": b.Nashecollection,
  ordinaryproduct: b.OrdinaryProduct,
  "ordinary product": b.OrdinaryProduct,
  ppanther: b.Ppanther,
  "p panther": b.Ppanther,
  myne: b.Myne,
  mzaco: b.Mzaco,
  leon: b.Leon,
  minilet: b.Minilet,
  homeboyattire: b.Homeboyattire,
  "homeboy attire": b.Homeboyattire,
  designkaf: b.Designkaf,
  "design kaf": b.Designkaf,
  slack: b.Slack,
  fufa: b.Fufa,
  fullslang: b.Fullslang,
  "full slang": b.Fullslang,
  kulture: b.Kulture,
  kato: b.Kato,
  riddle: b.Riddle,
  replica: b.Replica,
  kangaroo: b.Kangaroo,
  azelea: b.Azelea,
  beindie: b.BeIndie,
  "be indie": b.BeIndie,
  asili: b.Asili,
  stache: b.Stache,
  nspired: b.Nspired,
  odd: b.Odd,
  silq: b.Silq,
  hrtbrk: b.Hrtbrk,
  "hrt brk": b.Hrtbrk,
  fools: b.Fools,
  pulp: b.Pulp,
  novencci: b.Novencci,
  feheconcept: b.FeheConcept,
  "fehe concept": b.FeheConcept,
  greaze: b.Greaze,
  illusion: b.Illusion,
  bazets: b.Bazets,
  lumaa: b.Lumaa,
  sass: b.Sass,
  kuji: b.Kuji,
  tamaa: b.Tamaa,
  alcamileon: b.Alcamileon,
  "al camileon": b.Alcamileon,
  clother: b.Clother,
  "99threads": b["99Threads"],
  "99 threads": b["99Threads"],
  thewpclub: b.Thewpclub,
  "the wp club": b.Thewpclub,
  "the wpclub": b.Thewpclub,
  locco: b.Locco,
  kika: b.Kika,
  antikka: b.Antikka,
  maisondousha: b.MaisonDousha,
  "maison dousha": b.MaisonDousha,
};

// findMissingBrands();
