export const categories: Record<string, string[]> = {
  jackets: ["jacket", "coat", "zip up", "zip-up", "sherpa"],
  vests: ["vest"],
  kimonos: ["kimono", "kaftan", "kaftans", "kuftan", "cape"],
  cardigans: ["cardigan"],
  blazers: ["blazer", "suit"],
  "t-shirts": ["t-shirt", "tee", "tshirt", "jersey"],
  tops: [
    "top",
    "bodysuit",
    "body-suit",
    "crop-top",
    "one-shoulder",
    "halter",
    "corset",
    "babytee",
    "baby tee",
  ],
  shirts: ["shirt", "shirts", "chemise", "chemis", "flannel", "overshirt"],
  polos: ["polo"],
  jeans: ["jeans", "denim", "jean"],
  pants: ["pants", "trousers", "parachutes", "parachute", "chutes"],
  cargos: ["cargo", "cargos"],
  shorts: ["shorts", "zip-n-rip", "jort", "jorts"],
  skirts: ["skirt", "skort"],
  sweatpants: ["sweatpants", "joggers", "jogger", "sweats"],
  leggings: ["leggings"],
  hoodies: ["hoodie"],
  crewnecks: ["crewneck", "crewnecks", "crew neck", "crew-neck"],
  sweaters: ["sweater", "pullover", "jumper"],
  sweatshirts: [
    "sweatshirt",
    "quarter zip",
    "quarter-zip",
    "quarterzip",
    "half zip",
  ],
  knitwear: ["knitwear"],
  shoes: [
    "shoe",
    "espadrille",
    "espadrilles",
    "heels",
    "slippers",
    "slipper",
    "flats",
    "sneakers",
    "sandals",
    "loafers",
    "mules",
    "clogs",
    "slides",
    "sliders",
    "flip-flops",
    "flip flop",
    "pantoufles",
  ],
  socks: ["sock", "socks"],
  boots: ["boot", "boots"],
  sets: ["set", "co-ord", "coord"],
  dresses: ["dress", "bodycon", "sundress"],
  jumpsuits: ["jumpsuit", "romper"],
  sportswear: ["sportswear", "sports"],
  tracksuits: ["tracksuit"],
  swimwear: [
    "swimwear",
    "swimsuit",
    "swim trunks",
    "swimshorts",
    "bikini",
    "burkini",
    "cover up",
    "cover-up",
    "coverup",
    "one piece",
    "swimming",
    "swim",
    "sarong",
    "wrap",
    "Tankini",
    "one-piece",
  ],
  pajamas: ["pajama", "pyjama", "pj"],
  hats: ["hat", "cap", "fedora"],
  scarves: ["scarf"],
  sunglasses: ["sunglass", "sunglasses", "glasses", "shades"],
  wallets: ["wallet", "cardholder", "card holder"],
  headbands: ["headband", "headbands", "bandana", "bandanna"],
  perfumes: ["perfume", "fragrance"],
  earrings: ["earring", "earrings"],
  necklaces: ["necklace", "charm", "choker", "chocker"],
  backpacks: ["backpack"],
  bags: ["bag", "tote", "cross-bag", "clutch", "purse", "pouch", "fanny pack"],
  tanks: ["tanktop", "tank", "tank-top", "bustier"],
  homeware: [
    "homeware",
    "rug",
    "pillowcase",
    "lamp",
    "cushion",
    "frame",
    "pouf",
    "mirror",
    "placemats",
  ],
  accessories: [
    "anklet",
    "bracelet",
    "belt",
    "gloves",
    "rings",
    "ring",
    "chain",
    "scrunchie",
  ],
  candles: ["candles", "candle"],
  loungewear: ["robe", "robes", "bathrobe", "isdal"],
  blouses: ["blouse"],
  "laptop sleeves": ["laptop sleeve", "envelope sleeve", "quilted sleeve"],
};

// Create a reverse mapping of aliases to their main categories
// export const CategoryAliasMap: Record<string, string> = Object.entries(
//   categories
// ).reduce(
//   (acc, [mainCategory, aliases]) => {
//     acc[mainCategory.toLowerCase()] = mainCategory;
//     aliases.forEach((alias) => {
//       acc[alias.toLowerCase()] = mainCategory;
//     });
//     return acc;
//   },
//   {} as Record<string, string>
// );

enum C {
  Jackets = "jackets",
  Vests = "vests",
  Kimonos = "kimonos",
  Cardigans = "cardigans",
  Blazers = "blazers",
  TShirts = "t-shirts",
  Tops = "tops",
  Shirts = "shirts",
  Polos = "polos",
  Jeans = "jeans",
  Pants = "pants",
  Cargos = "cargos",
  Shorts = "shorts",
  Skirts = "skirts",
  Sweatpants = "sweatpants",
  Leggings = "leggings",
  Hoodies = "hoodies",
  Crewnecks = "crewnecks",
  Sweaters = "sweaters",
  Sweatshirts = "sweatshirts",
  Knitwear = "knitwear",
  Shoes = "shoes",
  Socks = "socks",
  Boots = "boots",
  Sets = "sets",
  Dresses = "dresses",
  Jumpsuits = "jumpsuits",
  Sportswear = "sportswear",
  Tracksuits = "tracksuits",
  Swimwear = "swimwear",
  Pajamas = "pajamas",
  Hats = "hats",
  Scarves = "scarves",
  Sunglasses = "sunglasses",
  Wallets = "wallets",
  Headbands = "headbands",
  Perfumes = "perfumes",
  Earrings = "earrings",
  Necklaces = "necklaces",
  Backpacks = "backpacks",
  Bags = "bags",
  Tanks = "tanks",
  Homeware = "homeware",
  Accessories = "accessories",
  Candles = "candles",
  Loungewear = "loungewear",
  Blouses = "blouses",
  LaptopSleeves = "laptop sleeves",
}

export const categoryMatcher: Record<string, C> = {
  jackets: C.Jackets,
  jacket: C.Jackets,
  coat: C.Jackets,
  "zip up": C.Jackets,
  "zip-up": C.Jackets,
  sherpa: C.Jackets,
  vests: C.Vests,
  vest: C.Vests,
  kimonos: C.Kimonos,
  kimono: C.Kimonos,
  kaftan: C.Kimonos,
  kaftans: C.Kimonos,
  kuftan: C.Kimonos,
  cape: C.Kimonos,
  cardigans: C.Cardigans,
  cardigan: C.Cardigans,
  blazers: C.Blazers,
  blazer: C.Blazers,
  suit: C.Blazers,
  "t-shirts": C.TShirts,
  "t-shirt": C.TShirts,
  tees: C.TShirts,
  tee: C.TShirts,
  tshirt: C.TShirts,
  jersey: C.TShirts,
  tops: C.Tops,
  top: C.Tops,
  bodysuit: C.Tops,
  "body-suit": C.Tops,
  "crop-top": C.Tops,
  "one-shoulder": C.Tops,
  halter: C.Tops,
  corset: C.Tops,
  babytee: C.Tops,
  "baby tee": C.Tops,
  shirts: C.Shirts,
  shirt: C.Shirts,
  chemise: C.Shirts,
  chemis: C.Shirts,
  flannel: C.Shirts,
  overshirt: C.Shirts,
  polos: C.Polos,
  polo: C.Polos,
  jeans: C.Jeans,
  denim: C.Jeans,
  jean: C.Jeans,
  pants: C.Pants,
  trousers: C.Pants,
  parachutes: C.Pants,
  parachute: C.Pants,
  chutes: C.Pants,
  cargos: C.Cargos,
  cargo: C.Cargos,
  shorts: C.Shorts,
  "zip-n-rip": C.Shorts,
  jort: C.Shorts,
  jorts: C.Shorts,
  skirts: C.Skirts,
  skirt: C.Skirts,
  skort: C.Skirts,
  sweatpants: C.Sweatpants,
  joggers: C.Sweatpants,
  jogger: C.Sweatpants,
  sweats: C.Sweatpants,
  leggings: C.Leggings,
  hoodies: C.Hoodies,
  hoodie: C.Hoodies,
  crewnecks: C.Crewnecks,
  crewneck: C.Crewnecks,
  "crew neck": C.Crewnecks,
  "crew-neck": C.Crewnecks,
  sweaters: C.Sweaters,
  sweater: C.Sweaters,
  pullover: C.Sweaters,
  jumper: C.Sweaters,
  sweatshirts: C.Sweatshirts,
  sweatshirt: C.Sweatshirts,
  "quarter zip": C.Sweatshirts,
  "quarter-zip": C.Sweatshirts,
  quarterzip: C.Sweatshirts,
  "half zip": C.Sweatshirts,
  knitwear: C.Knitwear,
  shoes: C.Shoes,
  shoe: C.Shoes,
  espadrille: C.Shoes,
  espadrilles: C.Shoes,
  heels: C.Shoes,
  slippers: C.Shoes,
  slipper: C.Shoes,
  flats: C.Shoes,
  sneakers: C.Shoes,
  sandals: C.Shoes,
  loafers: C.Shoes,
  mules: C.Shoes,
  clogs: C.Shoes,
  slides: C.Shoes,
  sliders: C.Shoes,
  "flip-flops": C.Shoes,
  "flip flop": C.Shoes,
  pantoufles: C.Shoes,
  socks: C.Socks,
  sock: C.Socks,
  boots: C.Boots,
  boot: C.Boots,
  sets: C.Sets,
  set: C.Sets,
  "co-ord": C.Sets,
  coord: C.Sets,
  dresses: C.Dresses,
  dress: C.Dresses,
  bodycon: C.Dresses,
  sundress: C.Dresses,
  jumpsuits: C.Jumpsuits,
  jumpsuit: C.Jumpsuits,
  romper: C.Jumpsuits,
  sportswear: C.Sportswear,
  sports: C.Sportswear,
  tracksuits: C.Tracksuits,
  tracksuit: C.Tracksuits,
  swimwear: C.Swimwear,
  swimsuit: C.Swimwear,
  "swim trunks": C.Swimwear,
  swimshorts: C.Swimwear,
  bikini: C.Swimwear,
  burkini: C.Swimwear,
  "cover up": C.Swimwear,
  "cover-up": C.Swimwear,
  coverup: C.Swimwear,
  "one piece": C.Swimwear,
  swimming: C.Swimwear,
  swim: C.Swimwear,
  sarong: C.Swimwear,
  wrap: C.Swimwear,
  tankini: C.Swimwear,
  "one-piece": C.Swimwear,
  pajamas: C.Pajamas,
  pajama: C.Pajamas,
  pyjama: C.Pajamas,
  pj: C.Pajamas,
  hats: C.Hats,
  hat: C.Hats,
  cap: C.Hats,
  fedora: C.Hats,
  scarves: C.Scarves,
  scarf: C.Scarves,
  sunglasses: C.Sunglasses,
  sunglass: C.Sunglasses,
  glasses: C.Sunglasses,
  shades: C.Sunglasses,
  wallets: C.Wallets,
  wallet: C.Wallets,
  cardholder: C.Wallets,
  "card holder": C.Wallets,
  headbands: C.Headbands,
  headband: C.Headbands,
  bandana: C.Headbands,
  bandanna: C.Headbands,
  perfumes: C.Perfumes,
  perfume: C.Perfumes,
  fragrance: C.Perfumes,
  earrings: C.Earrings,
  earring: C.Earrings,
  necklaces: C.Necklaces,
  necklace: C.Necklaces,
  charm: C.Necklaces,
  choker: C.Necklaces,
  chocker: C.Necklaces,
  backpacks: C.Backpacks,
  backpack: C.Backpacks,
  bags: C.Bags,
  bag: C.Bags,
  tote: C.Bags,
  "cross-bag": C.Bags,
  clutch: C.Bags,
  purse: C.Bags,
  pouch: C.Bags,
  "fanny pack": C.Bags,
  tanks: C.Tanks,
  tanktop: C.Tanks,
  tank: C.Tanks,
  "tank-top": C.Tanks,
  bustier: C.Tanks,
  homeware: C.Homeware,
  rug: C.Homeware,
  pillowcase: C.Homeware,
  lamp: C.Homeware,
  cushion: C.Homeware,
  frame: C.Homeware,
  pouf: C.Homeware,
  mirror: C.Homeware,
  placemats: C.Homeware,
  accessories: C.Accessories,
  anklet: C.Accessories,
  bracelet: C.Accessories,
  belt: C.Accessories,
  gloves: C.Accessories,
  rings: C.Accessories,
  ring: C.Accessories,
  chain: C.Accessories,
  scrunchie: C.Accessories,
  candles: C.Candles,
  candle: C.Candles,
  loungewear: C.Loungewear,
  robe: C.Loungewear,
  robes: C.Loungewear,
  bathrobe: C.Loungewear,
  isdal: C.Loungewear,
  blouses: C.Blouses,
  blouse: C.Blouses,
  "laptop sleeves": C.LaptopSleeves,
  "laptop sleeve": C.LaptopSleeves,
  "envelope sleeve": C.LaptopSleeves,
  "quilted sleeve": C.LaptopSleeves,
};
