export const colors: Record<string, string[]> = {
  black: ["black", "charcoal", "kohl"],
  white: ["white", "vanilla", "snow"],
  red: ["brick", "burgandy", "burgundy", "maroon", "red", "wine"],
  blue: [
    "aqua",
    "babyblue",
    "blue",
    "blues",
    "ice",
    "navy",
    "teal",
    "turquoise",
    "electric",
    "denim",
    "sky",
    "nile",
    "electra",
    "azure",
  ],
  green: [
    "emerald",
    "green",
    "greens",
    "jade",
    "lime",
    "matcha",
    "mint",
    "pistachio",
    "sage",
    "hazel",
    "lush",
    "limoncello",
  ],
  cream: ["cream", "creme", "offwhite", "crepe"],
  beige: ["beige", "biege", "dune", "ecru"],
  nude: ["nude"],
  tan: ["camal", "camel", "tan", "havane"],
  brown: [
    "brown",
    "coffee",
    "marron",
    "cinnamon",
    "cacao",
    "cafe",
    "mocha",
    "khaki",
  ],
  yellow: ["cuman", "cumin", "lemonade", "mustard", "yellow", "sand"],
  gold: ["gold"],
  gray: ["butter", "gray", "grey"],
  olive: ["army", "olive"],
  orange: ["orange", "peach", "coral"],
  pink: [
    "bubblegum",
    "fuchia",
    "fuchsia",
    "fushia",
    "pink",
    "rose",
    "simon",
    "cotton candy",
  ],
  purple: [
    "lavendar",
    "lavender",
    "lilac",
    "magneta",
    "purple",
    "eggplant",
    "indigo",
  ],
  silver: ["silver"],
  other: [
    "kashmir",
    "leopard",
    "multicolor",
    "printed",
    "rainbow",
    "transparent",
  ],
};

enum C {
  Black = "black",
  White = "white",
  Red = "red",
  Blue = "blue",
  Green = "green",
  Cream = "cream",
  Beige = "beige",
  Nude = "nude",
  Tan = "tan",
  Brown = "brown",
  Yellow = "yellow",
  Gold = "gold",
  Gray = "gray",
  Olive = "olive",
  Orange = "orange",
  Pink = "pink",
  Purple = "purple",
  Silver = "silver",
  Other = "other",
}

export const colorMatcher: Record<string, C> = {
  // Black
  black: C.Black,
  blacks: C.Black,
  charcoal: C.Black,
  charcoals: C.Black,
  kohl: C.Black,
  kohls: C.Black,

  // White
  white: C.White,
  whites: C.White,
  vanilla: C.White,
  vanillas: C.White,
  snow: C.White,

  // Red
  brick: C.Red,
  bricks: C.Red,
  burgandy: C.Red,
  burgundy: C.Red,
  burgundies: C.Red,
  maroon: C.Red,
  maroons: C.Red,
  red: C.Red,
  reds: C.Red,
  wine: C.Red,
  wines: C.Red,

  // Blue
  aqua: C.Blue,
  aquas: C.Blue,
  babyblue: C.Blue,
  "baby blue": C.Blue,
  "baby blues": C.Blue,
  blue: C.Blue,
  blues: C.Blue,
  ice: C.Blue,
  navy: C.Blue,
  navies: C.Blue,
  teal: C.Blue,
  teals: C.Blue,
  turquoise: C.Blue,
  turquoises: C.Blue,
  electric: C.Blue,
  electrics: C.Blue,
  denim: C.Blue,
  denims: C.Blue,
  sky: C.Blue,
  nile: C.Blue,
  electra: C.Blue,
  electras: C.Blue,
  azure: C.Blue,
  azures: C.Blue,

  // Green
  emerald: C.Green,
  emeralds: C.Green,
  green: C.Green,
  greens: C.Green,
  jade: C.Green,
  jades: C.Green,
  lime: C.Green,
  limes: C.Green,
  matcha: C.Green,
  matchas: C.Green,
  mint: C.Green,
  mints: C.Green,
  pistachio: C.Green,
  pistachios: C.Green,
  sage: C.Green,
  sages: C.Green,
  hazel: C.Green,
  hazels: C.Green,
  lush: C.Green,
  limoncello: C.Green,
  limoncellos: C.Green,

  // Cream
  cream: C.Cream,
  creams: C.Cream,
  creme: C.Cream,
  cremes: C.Cream,
  offwhite: C.Cream,
  "off white": C.Cream,
  "off whites": C.Cream,
  crepe: C.Cream,
  crepes: C.Cream,

  // Beige
  beige: C.Beige,
  beiges: C.Beige,
  biege: C.Beige,
  bieges: C.Beige,
  dune: C.Beige,
  dunes: C.Beige,
  ecru: C.Beige,
  ecrus: C.Beige,

  // Nude
  nude: C.Nude,
  nudes: C.Nude,

  // Tan
  camal: C.Tan,
  camals: C.Tan,
  camel: C.Tan,
  camels: C.Tan,
  tan: C.Tan,
  tans: C.Tan,
  havane: C.Tan,
  havanes: C.Tan,

  // Brown
  brown: C.Brown,
  browns: C.Brown,
  coffee: C.Brown,
  coffees: C.Brown,
  marron: C.Brown,
  marrons: C.Brown,
  cinnamon: C.Brown,
  cinnamons: C.Brown,
  cacao: C.Brown,
  cacaos: C.Brown,
  cafe: C.Brown,
  cafes: C.Brown,
  mocha: C.Brown,
  mochas: C.Brown,
  khaki: C.Brown,
  khakis: C.Brown,

  // Yellow
  cuman: C.Yellow,
  cumans: C.Yellow,
  cumin: C.Yellow,
  cumins: C.Yellow,
  lemonade: C.Yellow,
  lemonades: C.Yellow,
  mustard: C.Yellow,
  mustards: C.Yellow,
  yellow: C.Yellow,
  yellows: C.Yellow,
  sand: C.Yellow,
  sands: C.Yellow,
  "butter yellow": C.Yellow,
  "butter yellows": C.Yellow,
  butteryellow: C.Yellow,

  // Gold
  gold: C.Gold,
  golds: C.Gold,

  // Gray
  butter: C.Gray,
  butters: C.Gray,
  gray: C.Gray,
  grays: C.Gray,
  grey: C.Gray,
  greys: C.Gray,

  // Olive
  army: C.Olive,
  olive: C.Olive,
  olives: C.Olive,

  // Orange
  orange: C.Orange,
  oranges: C.Orange,
  peach: C.Orange,
  peaches: C.Orange,
  coral: C.Orange,
  corals: C.Orange,

  // Pink
  bubblegum: C.Pink,
  bubblegums: C.Pink,
  fuchia: C.Pink,
  fuchias: C.Pink,
  fuchsia: C.Pink,
  fuchsias: C.Pink,
  fushia: C.Pink,
  fushias: C.Pink,
  pink: C.Pink,
  pinks: C.Pink,
  rose: C.Pink,
  roses: C.Pink,
  simon: C.Pink,
  simons: C.Pink,
  "cotton candy": C.Pink,
  "cotton candies": C.Pink,

  // Purple
  lavendar: C.Purple,
  lavendars: C.Purple,
  lavender: C.Purple,
  lavenders: C.Purple,
  lilac: C.Purple,
  lilacs: C.Purple,
  magneta: C.Purple,
  magnetas: C.Purple,
  purple: C.Purple,
  purples: C.Purple,
  eggplant: C.Purple,
  eggplants: C.Purple,
  indigo: C.Purple,
  indigos: C.Purple,

  // Silver
  silver: C.Silver,
  silvers: C.Silver,

  // Other
  kashmir: C.Other,
  kashmirs: C.Other,
  leopard: C.Other,
  leopards: C.Other,
  multicolor: C.Other,
  multicolors: C.Other,
  printed: C.Other,
  rainbow: C.Other,
  rainbows: C.Other,
  transparent: C.Other,
};
