const materials = {
  cotton: ["damour", "cotton", "cottons"],
  linen: ["linen", "linens"],
  denim: ["denim", "denims"],
  leather: ["leather", "leathers"],
  jersey: ["jersey", "jerseys"],
  twill: ["twill", "twill"],
  gabardine: ["gabardine", "geberdine", "gabardines"],
  lycra: ["lycra", "lycras"],
  melton: ["melton", "meltons"],
  poplin: ["poplin", "poplins"],
  rosaline: ["rosaline", "rosalines"],
  satin: ["satin", "satins"],
  silk: ["silk", "silks"],
  cashmere: ["cashmere", "cashmeres"],
  chiffon: ["chiffon", "chiffons"],
  wool: ["wool", "wools"],
  crochet: ["crochet", "crochets"],
  knitted: ["knitted", "knit", "knits"],
};

enum m {
  Cotton = "cotton",
  Linen = "linen",
  Denim = "denim",
  Leather = "leather",
  Jersey = "jersey",
  Twill = "twill",
  Gabardine = "gabardine",
  Lycra = "lycra",
  Melton = "melton",
  Poplin = "poplin",
  Rosaline = "rosaline",
  Satin = "satin",
  Silk = "silk",
  Cashmere = "cashmere",
  Chiffon = "chiffon",
  Wool = "wool",
  Crochet = "crochet",
  Knitted = "knitted",
}

export const materialMatcher: Record<string, m> = {
  damour: m.Cotton,
  cotton: m.Cotton,
  cottons: m.Cotton,
  linen: m.Linen,
  linens: m.Linen,
  denim: m.Denim,
  denims: m.Denim,
  leather: m.Leather,
  leathers: m.Leather,
  jersey: m.Jersey,
  jerseys: m.Jersey,
  twill: m.Twill,
  gabardine: m.Gabardine,
  geberdine: m.Gabardine,
  gabardines: m.Gabardine,
  lycra: m.Lycra,
  lycras: m.Lycra,
  melton: m.Melton,
  meltons: m.Melton,
  poplin: m.Poplin,
  poplins: m.Poplin,
  rosaline: m.Rosaline,
  rosalines: m.Rosaline,
  satin: m.Satin,
  satins: m.Satin,
  silk: m.Silk,
  silks: m.Silk,
  cashmere: m.Cashmere,
  cashmeres: m.Cashmere,
  chiffon: m.Chiffon,
  chiffons: m.Chiffon,
  wool: m.Wool,
  wools: m.Wool,
  crochet: m.Crochet,
  crochets: m.Crochet,
  knitted: m.Knitted,
  knit: m.Knitted,
  knits: m.Knitted,
};
