-- CreateEnum
CREATE TYPE "ApplicantStatus" AS ENUM ('PENDING', 'EMAIL_SENT', 'ONLINE_INTERVIEW_SCHEDULED', 'ONLINE_INTERVIEW_COMPLETED', 'IN_PERSON_INTERVIEW_SCHEDULED', 'IN_PERSON_INTERVIEW_COMPLETED', 'HIRED', 'REJECTED');

-- AlterTable
ALTER TABLE "Applicant" ADD COLUMN     "status" "ApplicantStatus" NOT NULL DEFAULT 'PENDING';
